# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: ""
# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
baseurl: ""
# Google tracking id
google-tracking-id: false
#############
# HTML Head #
#############
lang: "en"
author: "Bianca Kang"
title: "Bianca Kang"
description:
  "some things about me"
keywords: ""
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/beach.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: false
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "hello! i'm happy to see you here."
me-img: "/img/jetpacktocat.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: False
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
disqus-shortname: False
syntax-highlight: False
############
# Timeline #
############
events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "your@email.here"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  ""
author_blurb_image: ""
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/kirillias"
  - icon: "linkedin"
    url: "https://www.linkedin.com/bianca-kang"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Research: "research"
  Posts: "latest-post"
  #Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
  - timeline
# Pagination path
paginate_path: "postings/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
